#数据库连接参数
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#自定义log
logging:
  pattern:
    console: "%d - %msg%n"
  #path: e:/
  file:
    max-size: 5MB
  level:
    #这里可以是包名也可以是类名
    com.lonely: info
  path: d:/logbackLog/log

#mybatis配置
mybatis:
  #实体类所做包
  type-aliases-package: com.zht.logback.entity
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*.xml